services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"

  back-service-wishlists:
    build:
      context: .  # Указываем корень проекта как контекст сборки
      dockerfile: docker-files/Go.Dockerfile
      args:
        MODULE_PATH: ${MODULE_PATH}
        SERVICE_PATH: ${SERVICE_PATH}
    ports:
      - "${BACK_SERVICE_WISHLISTS_PORT}:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NAME: "Alex"
    volumes:
      - ${MODULE_PATH}/go.mod:/app/go.mod
      - ${MODULE_PATH}/go.sum:/app/go.sum
      - ${MODULE_PATH}/main.go:/app/main.go
      - ${MODULE_PATH}/controllers:/app/controllers
      - ${MODULE_PATH}/docs:/app/docs
      - ${MODULE_PATH}/models:/app/models
      - ${MODULE_PATH}/routes:/app/routes
volumes:
  db_data:
