// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/wishlists": {
            "get": {
                "description": "Get a list of all wishlists",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wishlists"
                ],
                "summary": "Get all wishlists",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Wishlist"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Wishlist": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Время создания записи, автоматически управляется GORM",
                    "type": "string"
                },
                "description": {
                    "description": "Описание списка подарков, может быть NULL",
                    "type": "string"
                },
                "id": {
                    "description": "Уникальный идентификатор списка подарков",
                    "type": "integer"
                },
                "name": {
                    "description": "Название списка подарков",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Время последнего обновления записи, автоматически управляется GORM",
                    "type": "string"
                },
                "userID": {
                    "description": "Внешний ключ, указывающий на пользователя",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
